### ISSUE TITLE
[Feature request] Add WorkingDirectory for Service section

### ISSUE THREAD

**Issue by weewoo-meow** [NunuM/my-systemd-service-file-generator#2]
Please add a field where I can type in the working directory for my service. Thanks!

**Comment by NunuM** [comment]
Hi @miny1997,

If I understand correctly, have you tried to open the service options, by clicking on plus icon and select `WorkingDirectory` options?

![Screenshot from 2022-04-19 16-51-38](https://user-images.githubusercontent.com/15203554/164044674-20753885-3048-4cd1-9efc-52c5c3fef4a7.png)
