### ISSUE TITLE
[Feature Request] Where to put the generated file

### ISSUE THREAD

**Issue by igoro00** [NunuM/my-systemd-service-file-generator#3]
People(including me) use your site because they don't care to learn how to create systemd services themselves. It would be nice to show where should I put the file it generated.
It's not hard to google it but the next time I'll have to make a service I'm gonna forget that it's supposed to go in `/etc/systemd/system/nameOfMyService.service`.

**Comment by NunuM** [comment]
Hi @igoro00

Thank you. You're right! I will add a short description about the steps to do after download the service file.

Thank you
