### ISSUE TITLE
The preview makes unnecessary new lines when copying

### ISSUE THREAD

**Issue by igoro00** [NunuM/my-systemd-service-file-generator#4]
You're using <p> for every line of the file. When copying, it looks like this:
![image](https://user-images.githubusercontent.com/35789870/169082810-5dfe1821-1847-418e-8211-681dd4d3947f.png)

It should look like this:
![image](https://user-images.githubusercontent.com/35789870/169083014-14438166-dd5d-4f01-9417-a39ee183418f.png)

You should use `<p>` for every section, not line, and maybe `<br>` after every line

**Comment by NunuM** [comment]
Hey @igoro00 

Yes, this behavior I have notice since the beginning, but the sed resolved this form me :). Yes I'll fix this. Thank you once more. I'm creating a new branch to resolve this issue if you review it it will be very nice of you 👍

**Comment by NunuM** [comment]
merged and deployed 👍
